// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onBlueLEDChange();

float boardHUMID;
float boardTEMP;
bool blueLED;

void initProperties(){

  ArduinoCloud.addProperty(boardHUMID, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(boardTEMP, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(blueLED, READWRITE, ON_CHANGE, onBlueLEDChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
